[project]
authors = [{name = "sinty", email = "sintysage@gmail.com"}]
dependencies = []
name = "quanto"
requires-python = ">= 3.12"
version = "0.1.0"

# [build-system]
# build-backend = "hatchling.build"
# requires = ["hatchling"]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64"]

# [tool.pixi.pypi-dependencies]
# quanto = { path = ".", editable = true }

[tool.pixi.feature.main.tasks]
registe_kernel = "python -m ipykernel install --user --name main --display-name \"Python main\""

[tool.pixi.feature.quarto.tasks]
preview_site = "quarto preview"
render_site = "quarto render"

[tool.pixi.tasks]

[tool.pixi.dependencies]
boto3 = ">=1.43.81,<2"

[tool.pixi.environments]
default = { solve-group = "default" }
main = { features = ["main"], solve-group = "default" }
test = { features = ["test"], solve-group = "default" }
ml = { features = ["ml"], solve-group = "default" }
quarto = { features = ["quarto", "versioning"], solve-group = "default" } 

[tool.pixi.feature.main.dependencies]
polars = ">=1.44.1,<2"
pandas = ">=3.0.5,<4"
ruff = ">=0.16.5,<0.17"
ipython = ">=9.16.1,<10"
matplotlib = ">=3.11.1,<4"
seaborn = ">=0.13.2,<0.14"
ipykernel = ">=7.3.0,<8"

[tool.pixi.feature.ml.dependencies]
pytorch = ">=2.13.0,<3"
xgboost = ">=3.4.1,<4"
lightgbm = ">=4.7.0,<5"
scikit-learn = ">=1.9.0,<2"
ipykernel = ">=7.3.0,<8"

[tool.pixi.feature.versioning.dependencies]
dvc = ">=3.67.1,<4"
boto3 = ">=1.43.81,<2"

[tool.pixi.feature.quarto.dependencies]
quarto = ">=1.9.38,<2"
pyyaml = ">=6.0.3,<7"
nbformat = ">=5.11.1,<6"
nbclient = ">=0.11.0,<0.12"


[dependency-groups]
test = ["pytest>=9.1.1,<10"]
