{
  "hash": "4dbb81810de6d8580a4fcca606239aa6",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Finite Population Correction\"\ndescription: >-\n  If the probability of a customer exceeding their credit limit is 0.05, and we\n  randomly select 400 orders from a population of 3,500 orders, what is the\n  probability that between 15 and 25 customers will exceed their credit limit?\n  Use the Finite Population Correction Factor.\ncategories: [Tutorial, Stats, Task]\n---\n\n## Task\n\n> If the probability of a customer exceeding their credit limit is 0.05, and we\n> randomly select 400 orders from a population of 3,500 orders, what is the\n> probability that between 15 and 25 customers will exceed their credit limit?\n> Use the Finite Population Correction Factor.\n\n## 1. Making variables\n\n::: {.panel-tabset}\n## Math\n\n> If the probability of a customer exceeding their credit limit is [0.05]{.y},\n> and we randomly select [400]{.g} orders from a population of [3,500]{.b}\n> orders, what is the probability that between 15 and 25 customers will exceed\n> their credit limit? Use the Finite Population Correction Factor.\n\n- Population size: [N = 3500]{.b}\n- Sample size: [n = 400]{.g}\n- Probability of \"success\" (exceeding credit limit): [p = 0.05]{.y}\n\nBecause we are sampling **without replacement** from a finite population, and\n\n$$\n  \\frac{n}{N} = \\frac{400}{3500} \\approx 0.114 > 0.05,\n$$\n\nwe should use the [Finite Population Correction Factor\n(FPC)](https://share.google/aimode/pD9HMArupLm0LuR9i).\n\n## Code\n\n::: {#imports .cell execution_count=1}\n``` {.python .cell-code}\n# Just libraries to work with :)\nimport matplotlib.pyplot as plt\nimport numpy as np\nimport pandas as pd\nfrom scipy.stats import binom, hypergeom, norm\nimport seaborn as sns\nsns.set_theme(style=\"whitegrid\")\n\nclass Helper:\n    import os\n    import pathlib\n    from typing import Final\n\n    import boto3\n    from IPython.display import Markdown\n\n    BUCKET_NAME: Final = os.getenv(\"BUCKET_NAME\")\n    AWS_S3_ENDPOINT_URL: Final = os.getenv(\"AWS_S3_ENDPOINT_URL\")\n    QUARTO_DOCUMENT_FILE: Final = os.getenv(\"QUARTO_DOCUMENT_FILE\")\n\n    SAVE_DIR = \"artifacts/\" + pathlib.Path(QUARTO_DOCUMENT_FILE).stem\n\n    s3_client = boto3.client(\n        \"s3\",\n        endpoint_url=AWS_S3_ENDPOINT_URL,\n    )\n\n    try:\n        response = s3_client.list_objects_v2(\n            Bucket=BUCKET_NAME,\n        )\n\n    except Exception as e:\n        print(f\"Error connecting to S3: {e}\")\n\n    def upload_file(\n        self, file_path: str, obj_name: str, content_type: str = \"image/png\"\n    ):\n        \"\"\"Upload a local file to the configured S3 bucket.\n\n        The file is stored under the key ``{SAVE_DIR}/{plot_name}``,\n        where ``SAVE_DIR`` is derived from the current Quarto document's filename.\n\n        Args:\n            file_path: Path to the local file to upload.\n            plot_name: Name to use as the S3 object key (within ``SAVE_DIR``).\n            content_type: MIME type to set for the uploaded object.\n                Defaults to ``\"image/png\"``.\n\n        Returns:\n            None\n        \"\"\"\n\n        self.s3_client.upload_file(\n            Filename=file_path,\n            Bucket=self.BUCKET_NAME,\n            Key=f\"{self.SAVE_DIR}/{obj_name}\",\n            ExtraArgs={\"ContentType\": content_type},\n        )\n\n        return f\"{self.AWS_S3_ENDPOINT_URL}/{self.BUCKET_NAME}/{self.SAVE_DIR}/{obj_name}\"\n\n    def upload_visualize(\n        self,\n        file_path: str,\n        obj_name: str,\n        content_type: str = \"image/png\",\n        is_preview: bool = False,\n    ):\n        obj_ref = self.upload_file(file_path, obj_name, content_type)\n\n        if is_preview:\n            return self.Markdown(f\"![]({obj_ref}){{.preview-image}}\")\n        else:\n            return self.Markdown(f\"![]({obj_ref})\")\n\n\nhelper = Helper()\n\n```\n:::\n\n\n::: {#cell-rrr .cell execution_count=2}\n``` {.python .cell-code}\nN = 3500\nn = 400\np = 0.05\nK = int(round(p * N))\n\n# Build a tidy DataFrame of the given parameters\ndf = pd.DataFrame(\n    {\n        \"Parameter\": [\n            \"Population size N\",\n            \"Sample size n\",\n            \"Success probability p\",\n            \"Population successes K\",\n        ],\n        \"Variable\": [\"N\", \"n\", \"p\", \"K\"],\n        \"Value\": [N, n, p, K],\n    }\n)\ndf\n```\n\n::: {#rrr .cell-output .cell-output-display execution_count=2}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Parameter</th>\n      <th>Variable</th>\n      <th>Value</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>Population size N</td>\n      <td>N</td>\n      <td>3500.00</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>Sample size n</td>\n      <td>n</td>\n      <td>400.00</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>Success probability p</td>\n      <td>p</td>\n      <td>0.05</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>Population successes K</td>\n      <td>K</td>\n      <td>175.00</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n:::\n\n::: {.callout-note}\nThis is just an example. Params are different.\n:::\n\n[FPC Function](fpc_function.qmd)\n\n## 2. Check whether the normal approximation is appropriate\n\n::: {.panel-tabset}\n## Math\n\nFor a normal approximation to the binomial/hypergeometric distribution, we\nusually require:\n\n$$\n  np \\ge 5 \\quad \\text{and} \\quad n(1-p) \\ge 5\n$$\n\nCompute:\n\n$$\n  np = 400(0.05) = 20\n$$\n\n$$\n  n(1-p) = 400(0.95) = 380\n$$\n\nBoth are well above 5, so the normal approximation is reasonable. Below is an\nexample\n\n## Code\n\n::: {#9e7ff2b0 .cell execution_count=3}\n``` {.python .cell-code}\nfpc_ratio = n / N\nnp_check = n * p\nnq_check = n * (1 - p)\n\ndf_checks = pd.DataFrame({\n    \"Check\": [\n        \"Sampling fraction n/N\",\n        \"Expected successes np\",\n        \"Expected failures n(1-p)\"\n    ],\n    \"Statistic\": [\"n/N\", \"np\", \"n(1-p)\"],\n    \"Value\": [fpc_ratio, np_check, nq_check],\n    \"Decision / Note\": [\n        \"Use FPC\" if fpc_ratio > 0.05 else \"No FPC needed\",\n        \"OK\" if np_check >= 5 else \"Too small\",\n        \"OK\" if nq_check >= 5 else \"Too small\"\n    ]\n})\n\ndf_checks\n```\n\n::: {.cell-output .cell-output-display execution_count=3}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Check</th>\n      <th>Statistic</th>\n      <th>Value</th>\n      <th>Decision / Note</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>Sampling fraction n/N</td>\n      <td>n/N</td>\n      <td>0.114286</td>\n      <td>Use FPC</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>Expected successes np</td>\n      <td>np</td>\n      <td>20.000000</td>\n      <td>OK</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>Expected failures n(1-p)</td>\n      <td>n(1-p)</td>\n      <td>380.000000</td>\n      <td>OK</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n:::\n\n[normal_approximation](normal_approximation.qmd)\n\n## 3. Compute the mean\n\n::: {.panel-tabset}\n# Math\n\nThe expected number of customers who exceed the limit is:\n\n$$\n  \\mu = np\n$$\n\n$$\n  \\mu = 400(0.05) = 20\n$$\n\nSo we expect about **20 customers** in the sample to exceed the credit limit.\n\n# Code\n\n::: {#step3 .cell execution_count=4}\n``` {.python .cell-code}\nmu = n * p\nprint(f\"mu = np = {mu}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nmu = np = 20.0\n```\n:::\n:::\n\n\n:::\n\n## 4. Compute the standard deviation with the FPC\n\n::: {.panel-tabset}\n# Math\n\nThe variance of the number of successes in a sample from a finite population is:\n\n$$\n  \\sigma^2 = np(1-p)\\left(\\frac{N-n}{N-1}\\right)\n$$\n\nThe factor $\\frac{N-n}{N-1}$ is the **Finite Population Correction Factor**.\n\nFirst calculate the FPC:\n\n$$\n  \\frac{N-n}{N-1} = \\frac{3500-400}{3500-1} = \\frac{3100}{3499} \\approx 0.8860\n$$\n\nNext calculate the usual binomial variance:\n\n$$\n  np(1-p) = 400(0.05)(0.95) = 19\n$$\n\nNow apply the correction:\n\n$$\n  \\sigma^2 = 19(0.8860) \\approx 16.8334\n$$\n\nTake the square root to get the standard deviation:\n\n$$\n  \\sigma = \\sqrt{16.8334} \\approx 4.10\n$$\n\n# Code\n\n::: {#cell-step4 .cell execution_count=5}\n``` {.python .cell-code}\nfpc = (N - n) / (N - 1)\nvariance = n * p * (1 - p) * fpc\nsigma = np.sqrt(variance)\n\nresults = pd.DataFrame({\n    \"Quantity\": [\"FPC\", \"Variance (sigma^2)\", \"Std. deviation (sigma)\"],\n    \"Formula\": [\"(N-n)/(N-1)\", \"np(1-p)*FPC\", \"sqrt(sigma^2)\"],\n    \"Value\": [round(fpc, 6), round(variance, 4), round(sigma, 4)]\n})\n\nresults\n```\n\n::: {#step4 .cell-output .cell-output-display execution_count=5}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Quantity</th>\n      <th>Formula</th>\n      <th>Value</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>FPC</td>\n      <td>(N-n)/(N-1)</td>\n      <td>0.885967</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>Variance (sigma^2)</td>\n      <td>np(1-p)*FPC</td>\n      <td>16.833400</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>Std. deviation (sigma)</td>\n      <td>sqrt(sigma^2)</td>\n      <td>4.102900</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n:::\n\n::: {#cell-step10 .cell execution_count=6}\n``` {.python .cell-code}\n# Normal curve with FPC-adjusted sigma\nx = np.linspace(mu - 4 * sigma, mu + 4 * sigma, 500)\ny = norm.pdf(x, mu, sigma)\n\nfile_to_save = \"normal_approximation.png\"\nplot_name = file_to_save\n\nfig, ax = plt.subplots(figsize=(9, 4.5))\nsns.lineplot(x=x, y=y, color=\"steelblue\", lw=2.5, ax=ax)\n\n# ±1 sigma band\nmask1 = (x >= mu - sigma) & (x <= mu + sigma)\nax.fill_between(x[mask1], y[mask1], color=\"seagreen\", alpha=0.25,\n                label=f\"μ ± 1σ = [{mu - sigma:.1f}, {mu + sigma:.1f}]\")\n\n# ±2 sigma lines\nfor k, c in [(1, \"seagreen\"), (2, \"darkorange\")]:\n    ax.axvline(mu - k * sigma, color=c, ls=\":\", lw=1.5)\n    ax.axvline(mu + k * sigma, color=c, ls=\":\", lw=1.5,\n               label=f\"μ ± {k}σ = [{mu - k*sigma:.1f}, {mu + k*sigma:.1f}]\")\n\n# Mean marker\nax.axvline(mu, color=\"crimson\", ls=\"--\", lw=2,\n           label=f\"Mean μ = {mu:.0f},  σ = {sigma:.2f}\")\n\nax.set_title(f\"Normal approximation with FPC:  N({mu:.0f}, {sigma:.2f}²)\")\nax.set_xlabel(\"Customers exceeding credit limit\")\nax.set_ylabel(\"Density\")\nax.legend(fontsize=8)\nplt.savefig(file_to_save)\nplt.close(fig)\n\nhelper.upload_visualize(file_to_save, plot_name, )\n```\n\n::: {#step10 .cell-output .cell-output-display .cell-output-markdown execution_count=6}\n![](https://sinty-database.serveblog.net/quanto-site/artifacts/fin_pop_cor/normal_approximation.png)\n:::\n:::\n\n\n## 5. Set up the probability and apply continuity correction\n\n::: {.panel-tabset}\n# Math\n\nWe want the probability that the number of customers exceeding the limit is\nbetween 15 and 25:\n\n$$\n  P(15 \\le X \\le 25)\n$$\n\nBecause $X$ is a **discrete** count but we are approximating it with a\n**continuous** normal distribution, we use a **continuity correction** ---\nexpand the interval by 0.5 on each side:\n\n$$\n  P(15 \\le X \\le 25) \\approx P(14.5 < X < 25.5)\n$$\n\n# Code\n\n::: {#cell-step5 .cell execution_count=7}\n``` {.python .cell-code}\na, b = 15, 25                    # inclusive bounds on the count X\na_cc, b_cc = a - 0.5, b + 0.5    # continuity-corrected bounds\n\ndf_cc = pd.DataFrame({\n    \"Bound\": [\"Lower\", \"Upper\"],\n    \"Original\": [a, b],\n    \"Continuity-corrected\": [a_cc, b_cc],\n})\ndf_cc\n```\n\n::: {#step5 .cell-output .cell-output-display execution_count=7}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Bound</th>\n      <th>Original</th>\n      <th>Continuity-corrected</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>Lower</td>\n      <td>15</td>\n      <td>14.5</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>Upper</td>\n      <td>25</td>\n      <td>25.5</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n:::\n\n## 6. Convert to Z-scores\n\n::: {.panel-tabset}\n# Math\n\nThe Z-score formula is:\n\n$$\n  Z = \\frac{X - \\mu}{\\sigma}\n$$\n\n**Lower bound:**\n\n$$\n  Z_{\\text{lower}} = \\frac{14.5 - 20}{4.10} = \\frac{-5.5}{4.10} \\approx -1.34\n$$\n\n**Upper bound:**\n\n$$\n  Z_{\\text{upper}} = \\frac{25.5 - 20}{4.10} = \\frac{5.5}{4.10} \\approx 1.34\n$$\n\nSo we need:\n\n$$\n  P(-1.34 < Z < 1.34)\n$$\n\n# Code\n\n::: {#cell-step6 .cell execution_count=8}\n``` {.python .cell-code}\nz_lower = (a_cc - mu) / sigma\nz_upper = (b_cc - mu) / sigma\n\ndf_z = pd.DataFrame({\n    \"Bound\": [\"Lower\", \"Upper\"],\n    \"X (corrected)\": [a_cc, b_cc],\n    \"Z = (X - mu) / sigma\": [round(z_lower, 4), round(z_upper, 4)],\n})\ndf_z\n```\n\n::: {#step6 .cell-output .cell-output-display execution_count=8}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Bound</th>\n      <th>X (corrected)</th>\n      <th>Z = (X - mu) / sigma</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>Lower</td>\n      <td>14.5</td>\n      <td>-1.3405</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>Upper</td>\n      <td>25.5</td>\n      <td>1.3405</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n:::\n\n## 7. Find the probability from the standard normal table\n\n::: {.panel-tabset}\n# Math\n\nUsing the standard normal CDF $\\Phi(z)$:\n\n$$\n  P(-1.34 < Z < 1.34) = \\Phi(1.34) - \\Phi(-1.34)\n$$\n\nBy symmetry, $\\Phi(-1.34) = 1 - \\Phi(1.34)$, so:\n\n$$\n  P(-1.34 < Z < 1.34) = 2\\,\\Phi(1.34) - 1\n$$\n\nFrom the standard normal table, $\\Phi(1.34) \\approx 0.9099$, therefore:\n\n$$\n  P(-1.34 < Z < 1.34) \\approx 2(0.9099) - 1 = 0.8198\n$$\n\n# Code\n\n::: {#cell-step7 .cell execution_count=9}\n``` {.python .cell-code}\nprob_normal = norm.cdf(z_upper) - norm.cdf(z_lower)\nprob_exact = hypergeom.cdf(b, N, K, n) - hypergeom.cdf(a - 1, N, K, n)\n\ndf_prob = pd.DataFrame({\n    \"Method\": [\"Normal approx. (FPC + CC)\", \"Exact hypergeometric\"],\n    \"Probability\": [round(prob_normal, 4), round(prob_exact, 4)],\n    \"Percentage\": [f\"{prob_normal:.2%}\", f\"{prob_exact:.2%}\"],\n})\ndf_prob\n```\n\n::: {#step7 .cell-output .cell-output-display execution_count=9}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Method</th>\n      <th>Probability</th>\n      <th>Percentage</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>Normal approx. (FPC + CC)</td>\n      <td>0.8199</td>\n      <td>81.99%</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>Exact hypergeometric</td>\n      <td>0.8213</td>\n      <td>82.13%</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n:::\n\n::: {#cell-step5-plot .cell execution_count=10}\n``` {.python .cell-code}\nsns.set_theme(style=\"whitegrid\")\n\n# Everything computed here, self-contained\nz_lo = (a_cc - mu) / sigma\nz_hi = (b_cc - mu) / sigma\nprob_range = norm.cdf(z_hi) - norm.cdf(z_lo)\n\nx = np.linspace(mu - 4 * sigma, mu + 4 * sigma, 500)\ny = norm.pdf(x, mu, sigma)\n\nfig, ax = plt.subplots(figsize=(9, 4.5))\nsns.lineplot(x=x, y=y, color=\"steelblue\", lw=2.5, ax=ax)\n\n# Shade the continuity-corrected target range\nmask = (x >= a_cc) & (x <= b_cc)\nax.fill_between(x[mask], y[mask], color=\"gold\", alpha=0.6,\n                label=f\"P({a_cc} < X < {b_cc}) ≈ {prob_range:.2f}\")\n\n# Bounds with z-score annotations\nfor bound, z, side in [(a_cc, z_lo, -1), (b_cc, z_hi, 1)]:\n    ax.axvline(bound, color=\"darkorange\", ls=\"--\", lw=2)\n    ax.annotate(f\"X = {bound}\\nz = {z:+.2f}\",\n                xy=(bound, norm.pdf(bound, mu, sigma)),\n                xytext=(bound + side * 3 * sigma, norm.pdf(bound, mu, sigma) + 0.02),\n                ha=\"center\", fontsize=9, color=\"darkorange\",\n                arrowprops=dict(arrowstyle=\"->\", color=\"darkorange\"))\n\n# Mean marker\nax.axvline(mu, color=\"crimson\", ls=\"-.\", lw=2, label=f\"Mean μ = {mu:.0f}\")\n\nax.set_title(f\"Target range on N({mu:.0f}, {sigma:.2f}²):  \"\n             f\"P({a} ≤ X ≤ {b}) ≈ {prob_range:.2f}\")\nax.set_xlabel(\"Customers exceeding credit limit\")\nax.set_ylabel(\"Density\")\nax.legend()\n\nfile_to_save = \"second.png\"\nplot_name = file_to_save\n\nplt.savefig(file_to_save)\nplt.close(fig)\n\nhelper.upload_visualize(file_to_save, plot_name, is_preview=True)\n```\n\n::: {#step5-plot .cell-output .cell-output-display .cell-output-markdown execution_count=10}\n![](https://sinty-database.serveblog.net/quanto-site/artifacts/fin_pop_cor/second.png){.preview-image}\n:::\n:::\n\n\n## 8. Equivalent sample-proportion method (optional check)\n\n::: {.panel-tabset}\n# Math\n\nWork with **sample proportions** instead of counts. The proportion range:\n\n$$\n  \\frac{15}{400} = 0.0375 \\quad \\text{to} \\quad \\frac{25}{400} = 0.0625\n$$\n\nStandard error of the sample proportion with FPC:\n\n$$\n  SE_{\\hat{p}} = \\sqrt{\\frac{p(1-p)}{n}\\left(\\frac{N-n}{N-1}\\right)}\n  = \\sqrt{\\frac{0.05(0.95)}{400}(0.8860)} \\approx 0.0103\n$$\n\nWith continuity correction:\n\n$$\n  \\frac{14.5}{400} = 0.03625, \\qquad \\frac{25.5}{400} = 0.06375\n$$\n\nZ-score:\n\n$$\n  Z = \\frac{0.06375 - 0.05}{0.0103} \\approx 1.34\n$$\n\nSame result as the count method.\n\n# Code\n\n::: {#cell-step8 .cell execution_count=11}\n``` {.python .cell-code}\nse_p = np.sqrt(p * (1 - p) / n * fpc)\nz_prop = ((b_cc / n) - p) / se_p\nprob_prop = 2 * norm.cdf(z_prop) - 1\n\ndf_prop = pd.DataFrame({\n    \"Quantity\": [\"SE of p-hat\", \"Z (upper)\", \"Probability\"],\n    \"Value\": [round(se_p, 5), round(z_prop, 4), round(prob_prop, 4)],\n})\ndf_prop\n```\n\n::: {#step8 .cell-output .cell-output-display execution_count=11}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Quantity</th>\n      <th>Value</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>SE of p-hat</td>\n      <td>0.01026</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>Z (upper)</td>\n      <td>1.34050</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>Probability</td>\n      <td>0.81990</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n:::\n\n## 9. Final answer\n\n::: {.panel-tabset}\n# Math\n\n$$\n  P(15 \\le X \\le 25) \\approx 0.8198\n$$\n\nSo the probability that between 15 and 25 customers exceed their credit limit is\napproximately:\n\n$$\n  \\boxed{0.82 \\text{ or } 82\\%}\n$$\n\nWithout the continuity correction the answer would be $\\approx 0.777$\n($77.7\\%$); the corrected value $0.82$ is more accurate for a discrete count.\n\n# Code\n\n::: {#cell-step9 .cell execution_count=12}\n``` {.python .cell-code}\nprob_no_cc = norm.cdf((b - mu) / sigma) - norm.cdf((a - mu) / sigma)\n\ndf_final = pd.DataFrame({\n    \"Answer\": [\"With continuity correction\", \"Without continuity correction\"],\n    \"Probability\": [round(prob_normal, 4), round(prob_no_cc, 4)],\n    \"Percentage\": [f\"{prob_normal:.2%}\", f\"{prob_no_cc:.2%}\"],\n})\ndf_final\n```\n\n::: {#step9 .cell-output .cell-output-display execution_count=12}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Answer</th>\n      <th>Probability</th>\n      <th>Percentage</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>With continuity correction</td>\n      <td>0.8199</td>\n      <td>81.99%</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>Without continuity correction</td>\n      <td>0.7770</td>\n      <td>77.70%</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n:::\n\n",
    "supporting": [
      "fin_pop_cor_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}